export {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Camera,
  Check,
  Copy,
  DownloadSimple as Download,
  FileText as FileIcon,
  Link as LinkIcon,
  LockKey as Lock,
  Plus,
  ShieldCheck as Shield,
  WifiHigh as Wifi,
  X as XIcon,
} from "@phosphor-icons/react";
